### PR TITLE
refactor: improve the auth component

### PR DESCRIPTION
**Pull request by boringContributor**
here a little improvement from my side and a quick little note regarding your auth component.

1. I tried to make it geist agnostic -> i do like geist but saw you want to shift away from it. The geist approach would be to use a Grid here but it is fine like that.
2. You explicitly check for empty spaces or a set input through regex which does not make any sense while using such a UI lib. Even if you move to chakra or material ui or any other ui lib, it is handled for you and this type of input check should be on the backend side only then. However if you'd like to make some manual checks it is fine as well but for this case it is not really useful
3. I would rather display a general toast regarding errors instead of printing the api response to the client, another option would be to use a Note (https://geist-ui.dev/en-us/components/note) above the login form.
4. I reverted the auth button to be filled initially which is a bit user friendlier ui/ux wise

feel free to make your changes and have fun on your project

### CODE REVIEW

**Comment by sampaioxsamuel** [comment]
Hey @boringContributor I did the PR to add the regex, I think it's useful at least to show an error before send to back end but I agree that it should be handled on back end

**Review by MaxLeiter — APPROVED** [review]

**Comment by MaxLeiter** [comment]
Thank you! This is great

**Comment by boringContributor** [comment]
ok but let me add your regex again, at least for the username

**Comment by MaxLeiter** [comment]
> ok but let me add your regex again, at least for the username

That’s fine with me, but can you make sure its also enforced on the backend?

**Comment by boringContributor** [comment]
this should be enough for now, however you should start using express a bit more, by adding middlewares and proper error delegating. For this use case it is sufficient though

**Comment by MaxLeiter** [comment]
@boringContributor I intend to move off of node eventually to something more lightweight so I’m not too worried at the moment, but thanks for the advice! I’ll be sure to keep it in mind for the future.

**Comment by boringContributor** [comment]
@MaxLeiter node is perfect for that. If you have a preferred programming language then i guess you can change but other than that i would stick with node. I would recommend having a look at NestJS (https://nestjs.com/) if you dont know it yet. It is very powerful and build around express. Have a look and if you want to help on the setup just ping me.

**Comment by MaxLeiter** [comment]
LGTM 🎉

**Pull request merged**
