### PR TITLE
Change post visibility

### LINKED ISSUE #64: Add ability to change post visibility

### PR DESCRIPTION
**Pull request by jazcarate**
Closes #64

Again with my awful UI 😅 
I tried aligning the buttons to the right, like the UX when creating. Cound't CSS 🙈.
I tried the UX of having a `ButtonDropdown` but felt... off. Cant really explain.

Test are missing. I know. I started with https://github.com/MaxLeiter/Drift/issues/79 but got a bit derailed with #64 😳 

### Change you own post
image

### A protected post
image

### Seeing another user's post
image

## Discussion point
It is weird that the links to the posts depend on the visibility. Now that we can change it, links will break.
Say I send you a link to `http://drift/post/**protected**/91b769ab-b96e-4222-8501-95b0749a920e` or `http://drift.com/post/**private**/91b769ab-b96e-4222-8501-95b0749a920e`, but then make it public; the old link will break.
I think any visibility should check the post ID and redirect accordingly to the _current_ visibility.

### CODE REVIEW

**Comment by MaxLeiter** [comment]
I'll comment on some ideas for an improved UX when I think on it some more, but as a response to `It is weird that the links to the posts depend on the visibility.`: I agree, and it's actually not necessary anymore. I did that as `public` and `unlisted` posts can be SSG, which I removed to simplify the Docker setup.

**Comment by jazcarate** [comment]
I removed the `margin`  of that button group (see image)
I added a delay loading
Made the visibility prop change; rather than the router recalculate
Made buttons be disabled, rather than appear and disappear when you change visibility

image

**Comment by MaxLeiter** [comment]
Looks great! Can you move the ButtonGroup to the right-side, similar to when creating a post?

I think this will eventually be moved to a proper edit page once I figure out post revisions, but it's great to have the functionality now.

**Comment by jazcarate** [comment]
Done :) 
image

**Pull request merged**
